INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES("When playing Cards Against Humanity with drunk people, it's always best to _________.",  1, "games", "tag", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("After breakfasting on _____, former governor Arnold Schwarzenegger loves to ______.",  2, "food", "celebrities", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("The most annoying thing about the person in front of me at Starbucks is ______.", 1, "people", "culture", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("If I only had my multitool right now, I could _____.", 1, "activities", "tag", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("I would probably _____ for a date with _____.", 2, "relationships", "tag", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("When I’m a parent, I’ll be sure I teach my kid to _____.", 1, "education", "parenting", "people", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("_____ is the next great potato chip flavor nobody is talking about.", 1, "food", "trends", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("The first plank of my new political party platform is about solving the problem of _______.", 1, "politics", "tag", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("I think it’s about time for _____ to make a comeback. ", 1, "trends", "culture", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("If I could ask President Trump one question, it would be: ______ ?", 1, "politics", "tag", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("The best thing about riding motorcycles in the rain is ______.", 1, "activities", "tag", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("When traveling with ______, it’s best to also pack a/some _____.", 2, "travel", "tag", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("Oh my gosh, I totally left for work without my ______ !", 1, "tag", "tag", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("I think _____ is/are an underrated look.",  1, "style", "trends", "culture", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("But seriously, ____ is an essential piece of any man’s wardrobe.", 1, "style", "fashion", "culture", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("The one fruit I’d want to have a conversation with would be _____.", 1, "food", "tag", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("The one thing you should never ask a priest is, ' __.'", 1, "religion", "tag", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("I sure wish ____ was socially acceptable.", 1, "culture", "people", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("The most beautiful flower smells like ____.", 1, "nature", "smells", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("Your one best skill that you don't list on your resume: _____", 1, "work", "tag", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("I really had to reconsider my relationship with my _______ when s/he/they gave me the worst gift ever: _______.", 2, "people", "relationships", "friends", "family", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("It's probably for the best that _____ are not allowed at petting zoos.", 1, "animals", "culture", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("Even if the deceased is extremely unlikeable, it's still very ill-advised at any funeral to say: _____ ",1, "people", "culture", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("The FDA is expected to approve _____, the first intentional flatulence-causing medicine.", 1, "drugs", "smells", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("There are way too many _____ in _____.", 2, "trends", "tag", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("The real cause of global warming is probably _____.", 1, "science", "weather", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("Sure, I'd definitely pay $50 for a _____ right now!", 1, "activities", "tag", "tag", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("You'd think by now Target would carry _____.", 1, "culture", "trends", "shopping", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("Retailers are still undecided on whether to sell soap that smells like _____.", 1, "culture", "trends", "smells", "shopping", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("Our exhaustive research has concluded that _____ champion athlete _____ would be an excellent spokesman for _____.", 3, "sports", "celebrities", "culture", "tag", "tag");
INSERT INTO questions (quest_text, blanks, tag1, tag2, tag3, tag4, tag5) VALUES ("Did you read the USA Today report that Depends undergarments can also be used to _____?", 1, "science", "culture", "tag", "tag", "tag");
