INSERT INTO questions (quest_text) VALUES("When playing Cards Against Humanity with drunk people, it's always best to _________.");
INSERT INTO questions (quest_text) VALUES ("After breakfasting on _____, former governor Arnold Schwarzenegger loves to ______.");
INSERT INTO questions (quest_text) VALUES ("The most annoying thing about the person in front of me at Starbucks is ______.");
INSERT INTO questions (quest_text) VALUES ("If I only had my multitool right now, I could _____.");
INSERT INTO questions (quest_text) VALUES ("I would probably _____ for a date with _____.");
INSERT INTO questions (quest_text) VALUES ("When I’m a parent, I’ll be sure I teach my kid to _____.");
INSERT INTO questions (quest_text) VALUES ("_____ is the next great potato chip flavor nobody is talking about.");
INSERT INTO questions (quest_text) VALUES ("The first plank of my new political party platform is about solving the problem of _______.");
INSERT INTO questions (quest_text) VALUES ("I think it’s about time for _____ to make a comeback. ");
INSERT INTO questions (quest_text) VALUES ("If I could ask President Trump one question, it would be: ______ ?");
INSERT INTO questions (quest_text) VALUES ("The best thing about riding motorcycles in the rain is ______.");
INSERT INTO questions (quest_text) VALUES ("When traveling with ______, it’s best to also pack a/some _____.");
INSERT INTO questions (quest_text) VALUES ("Oh my gosh, I totally left for work without my ______ !");
INSERT INTO questions (quest_text) VALUES ("I think _____ is/are an underrated look.");
INSERT INTO questions (quest_text) VALUES ("But seriously, ____ is an essential piece of any man’s wardrobe.");
INSERT INTO questions (quest_text) VALUES ("The one fruit I’d want to have a conversation with would be _____.");
INSERT INTO questions (quest_text) VALUES ("The one thing you should never ask a priest is, ' __.'");
INSERT INTO questions (quest_text) VALUES ("I sure wish ____ was socially acceptable.");
INSERT INTO questions (quest_text) VALUES ("The most beautiful flower smells like ____.");
INSERT INTO questions (quest_text) VALUES ("Your one best skill that you don't list on your resume: _____");
INSERT INTO questions (quest_text) VALUES ("I really had to reconsider my relationship with my _______ when s/he/they gave me the worst gift ever: _______.");
INSERT INTO questions (quest_text) VALUES ("It's probably for the best that _____ are not allowed at petting zoos.");
INSERT INTO questions (quest_text) VALUES ("Even if the deceased is extremely unlikeable, it's still very ill-advised at any funeral to say: _____ ");
INSERT INTO questions (quest_text) VALUES ("The FDA is expected to approve _____, the first intentional flatulence-causing medicine.");
INSERT INTO questions (quest_text) VALUES ("There are way too many _____ in _____.");
INSERT INTO questions (quest_text) VALUES ("The real cause of global warming is probably _____.");
INSERT INTO questions (quest_text) VALUES ("Sure, I'd definitely pay $50 for a _____ right now!");
INSERT INTO questions (quest_text) VALUES ("You'd think by now Target would carry _____.");
INSERT INTO questions (quest_text) VALUES ("Retailers are still undecided on whether to sell soap that smells like _____.");
INSERT INTO questions (quest_text) VALUES ("Our exhaustive research has concluded that _____ champion athlete _____ would be an excellent spokesman for _____.");
INSERT INTO questions (quest_text) VALUES ("Did you read the USA Today report that Depends undergarments can also be used to _____?");
